"""Services for the Parcel Package Tracking integration."""
import logging
import voluptuous as vol

from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.helpers import config_validation as cv

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

# Service schema for refresh
REFRESH_SCHEMA = vol.Schema({})

# Service schema for add_tracking
ADD_TRACKING_SCHEMA = vol.Schema(
    {
        vol.Required("carrier"): cv.string,
        vol.Required("tracking_number"): cv.string,
        vol.Required("description"): cv.string,
    }
)


async def async_setup_services(hass: HomeAssistant) -> None:
    """Set up services for the Parcel integration."""

    async def handle_refresh(call: ServiceCall) -> None:
        """Handle the refresh service call."""
        _LOGGER.debug("Handling refresh service call")
        # Refresh all coordinators
        for entry_id, coordinator in hass.data[DOMAIN].items():
            await coordinator.async_refresh()
            _LOGGER.debug("Refreshed coordinator for entry %s", entry_id)

    async def handle_add_tracking(call: ServiceCall) -> None:
        """Handle the add_tracking service call."""
        _LOGGER.debug("Handling add_tracking service call")
        # This is a placeholder - the current API doesn't support adding tracking numbers
        # We would need a different endpoint or method to implement this
        _LOGGER.warning(
            "The add_tracking service is not functional with the current API. "
            "This is a placeholder for future API capabilities."
        )

    # Register services
    hass.services.async_register(
        DOMAIN, "refresh", handle_refresh, schema=REFRESH_SCHEMA
    )
    
    hass.services.async_register(
        DOMAIN, "add_tracking", handle_add_tracking, schema=ADD_TRACKING_SCHEMA
    )


async def async_unload_services(hass: HomeAssistant) -> None:
    """Unload services for the Parcel integration."""
    # Remove services
    hass.services.async_remove(DOMAIN, "refresh")
    hass.services.async_remove(DOMAIN, "add_tracking")
